package task.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Bus;

@Mapper
public interface BusMapper {
    List<Bus> selectAllWithTrips();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUS
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int deleteByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUS
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int insert(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUS
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    Bus selectByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUS
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    List<Bus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUS
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int updateByPrimaryKey(Bus record);
}