package task.lt.mybatis.dao;

import java.util.List;
import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Driver;

@Mapper
public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 25 12:45:36 EEST 2022
     */
    int deleteByPrimaryKey(Integer driverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 25 12:45:36 EEST 2022
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 25 12:45:36 EEST 2022
     */
    Driver selectByPrimaryKey(Integer driverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 25 12:45:36 EEST 2022
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 25 12:45:36 EEST 2022
     */
    int updateByPrimaryKey(Driver record);
}