package task.lt.mybatis.dao;

import task.lt.mybatis.model.DriverBus;

import java.util.List;

public interface DriverBusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER_BUS
     *
     * @mbg.generated Mon Apr 25 14:30:11 EEST 2022
     */
    int insert(DriverBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER_BUS
     *
     * @mbg.generated Mon Apr 25 14:30:11 EEST 2022
     */
    List<DriverBus> selectAll();
}