package task.lt.mybatis.dao;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Flight;
import task.lt.mybatis.model.Ticket;

import java.util.List;

@Mapper
public interface FlightMapper {
    List<Flight> selectFlightsWithTickets();
    List<Ticket> selectTicketsByFlightId(@Param("flightId") Integer flightId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    Flight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    List<Flight> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int updateByPrimaryKey(Flight record);
}