package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.FlightLog;

import java.util.List;

@Mapper
public interface FlightLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT_LOG
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT_LOG
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int insert(FlightLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT_LOG
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    FlightLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT_LOG
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    List<FlightLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT_LOG
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int updateByPrimaryKey(FlightLog record);
}