package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Pilot;

import java.util.List;

@Mapper
public interface PilotMapper {
    List<Pilot> selectAllWithFlights();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    int deleteByPrimaryKey(Integer pilotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    int insert(Pilot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    Pilot selectByPrimaryKey(Integer pilotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    List<Pilot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    int updateByPrimaryKey(Pilot record);
}