package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.PilotPlane;

import java.util.List;

@Mapper
public interface PilotPlaneMapper {
    void deleteByPilotId(Integer pilotId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT_PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int insert(PilotPlane record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT_PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    List<PilotPlane> selectAll();
}