package task.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Plane;

import java.util.List;

@Mapper
public interface PlaneMapper {
    List<Plane> selectAllWithFlights();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int deleteByPrimaryKey(Integer planeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int insert(Plane record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    Plane selectByPrimaryKey(Integer planeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    List<Plane> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    int updateByPrimaryKey(Plane record);
}