package task.lt.mybatis.dao;

import java.util.List;
import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.Ticket;

@Mapper
public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    Ticket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    List<Ticket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TICKET
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int updateByPrimaryKey(Ticket record);
}