package task.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import task.lt.mybatis.model.TripLog;

@Mapper
public interface TripLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP_LOG
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP_LOG
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int insert(TripLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP_LOG
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    TripLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP_LOG
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    List<TripLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP_LOG
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    int updateByPrimaryKey(TripLog record);
}