package task.lt.mybatis.model;

public class Bus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BUS.BUS_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BUS.CURRENT_FUEL
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer currentFuel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BUS.PLATE_NUMBER
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private String plateNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BUS.BUS_ID
     *
     * @return the value of PUBLIC.BUS.BUS_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BUS.BUS_ID
     *
     * @param busId the value for PUBLIC.BUS.BUS_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BUS.CURRENT_FUEL
     *
     * @return the value of PUBLIC.BUS.CURRENT_FUEL
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getCurrentFuel() {
        return currentFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BUS.CURRENT_FUEL
     *
     * @param currentFuel the value for PUBLIC.BUS.CURRENT_FUEL
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setCurrentFuel(Integer currentFuel) {
        this.currentFuel = currentFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BUS.PLATE_NUMBER
     *
     * @return the value of PUBLIC.BUS.PLATE_NUMBER
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BUS.PLATE_NUMBER
     *
     * @param plateNumber the value for PUBLIC.BUS.PLATE_NUMBER
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }
}