package task.lt.mybatis.model;

import java.util.Date;

public class FlightLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.ARRIVAL_TIME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private String arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.CREATION_DATE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.DEPARTURE_TIME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private String departureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.NAME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer pilotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FLIGHT_LOG.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer planeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.ID
     *
     * @return the value of PUBLIC.FLIGHT_LOG.ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.ID
     *
     * @param id the value for PUBLIC.FLIGHT_LOG.ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.ARRIVAL_TIME
     *
     * @return the value of PUBLIC.FLIGHT_LOG.ARRIVAL_TIME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.ARRIVAL_TIME
     *
     * @param arrivalTime the value for PUBLIC.FLIGHT_LOG.ARRIVAL_TIME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.CREATION_DATE
     *
     * @return the value of PUBLIC.FLIGHT_LOG.CREATION_DATE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.CREATION_DATE
     *
     * @param creationDate the value for PUBLIC.FLIGHT_LOG.CREATION_DATE
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.DEPARTURE_TIME
     *
     * @return the value of PUBLIC.FLIGHT_LOG.DEPARTURE_TIME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.DEPARTURE_TIME
     *
     * @param departureTime the value for PUBLIC.FLIGHT_LOG.DEPARTURE_TIME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.NAME
     *
     * @return the value of PUBLIC.FLIGHT_LOG.NAME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.NAME
     *
     * @param name the value for PUBLIC.FLIGHT_LOG.NAME
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.PILOT_ID
     *
     * @return the value of PUBLIC.FLIGHT_LOG.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getPilotId() {
        return pilotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.PILOT_ID
     *
     * @param pilotId the value for PUBLIC.FLIGHT_LOG.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setPilotId(Integer pilotId) {
        this.pilotId = pilotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FLIGHT_LOG.PLANE_ID
     *
     * @return the value of PUBLIC.FLIGHT_LOG.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FLIGHT_LOG.PLANE_ID
     *
     * @param planeId the value for PUBLIC.FLIGHT_LOG.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }
}