package task.lt.mybatis.model;

public class PilotPlane {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT_PLANE.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer planeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT_PLANE.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer pilotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT_PLANE.PLANE_ID
     *
     * @return the value of PUBLIC.PILOT_PLANE.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT_PLANE.PLANE_ID
     *
     * @param planeId the value for PUBLIC.PILOT_PLANE.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT_PLANE.PILOT_ID
     *
     * @return the value of PUBLIC.PILOT_PLANE.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getPilotId() {
        return pilotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT_PLANE.PILOT_ID
     *
     * @param pilotId the value for PUBLIC.PILOT_PLANE.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setPilotId(Integer pilotId) {
        this.pilotId = pilotId;
    }
}