package task.lt.mybatis.model;

import java.util.List;

public class Pilot {
    private List<Flight> flights;

    public List<Flight> getFlights() {
        return flights;
    }

    public void setFlights(List<Flight> flights) {
        this.flights = flights;
    }

    private List<Plane> planes;

    public List<Plane> getPlanes() {
        return planes;
    }

    public void setPlanes(List<Plane> planes) {
        this.planes = planes;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    private Integer pilotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.CARD_NUMBER
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    private Integer cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.CELL_PHONE
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    private String cellPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.NAME
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.SURNAME
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.PILOT_ID
     *
     * @return the value of PUBLIC.PILOT.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public Integer getPilotId() {
        return pilotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.PILOT_ID
     *
     * @param pilotId the value for PUBLIC.PILOT.PILOT_ID
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public void setPilotId(Integer pilotId) {
        this.pilotId = pilotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.CARD_NUMBER
     *
     * @return the value of PUBLIC.PILOT.CARD_NUMBER
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public Integer getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.CARD_NUMBER
     *
     * @param cardNumber the value for PUBLIC.PILOT.CARD_NUMBER
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public void setCardNumber(Integer cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.CELL_PHONE
     *
     * @return the value of PUBLIC.PILOT.CELL_PHONE
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.CELL_PHONE
     *
     * @param cellPhone the value for PUBLIC.PILOT.CELL_PHONE
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.NAME
     *
     * @return the value of PUBLIC.PILOT.NAME
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.NAME
     *
     * @param name the value for PUBLIC.PILOT.NAME
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.SURNAME
     *
     * @return the value of PUBLIC.PILOT.SURNAME
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.SURNAME
     *
     * @param surname the value for PUBLIC.PILOT.SURNAME
     *
     * @mbg.generated Tue Apr 26 09:50:15 EEST 2022
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}