package task.lt.mybatis.model;

import java.util.List;

public class Plane {
    private List<Flight> flights;

    private List<Pilot> pilots;

    public List<Flight> getFlights() {
        return flights;
    }

    public void setFlights(List<Flight> flights) {
        this.flights = flights;
    }

    public List<Pilot> getPilots() {
        return pilots;
    }

    public void setPilots(List<Pilot> pilots) {
        this.pilots = pilots;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer planeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.CURRENT_FUEL
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private Integer currentFuel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.PLANE_NUMBER
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    private String planeNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.PLANE_ID
     *
     * @return the value of PUBLIC.PLANE.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.PLANE_ID
     *
     * @param planeId the value for PUBLIC.PLANE.PLANE_ID
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.CURRENT_FUEL
     *
     * @return the value of PUBLIC.PLANE.CURRENT_FUEL
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public Integer getCurrentFuel() {
        return currentFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.CURRENT_FUEL
     *
     * @param currentFuel the value for PUBLIC.PLANE.CURRENT_FUEL
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setCurrentFuel(Integer currentFuel) {
        this.currentFuel = currentFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.PLANE_NUMBER
     *
     * @return the value of PUBLIC.PLANE.PLANE_NUMBER
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public String getPlaneNumber() {
        return planeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.PLANE_NUMBER
     *
     * @param planeNumber the value for PUBLIC.PLANE.PLANE_NUMBER
     *
     * @mbg.generated Tue Apr 26 09:44:11 EEST 2022
     */
    public void setPlaneNumber(String planeNumber) {
        this.planeNumber = planeNumber;
    }
}