package task.lt.mybatis.model;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.IS_BOUGHT
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Boolean isBought;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.PRICE
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.SEAT
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer seat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TICKET.TRIP_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer tripId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.ID
     *
     * @return the value of PUBLIC.TICKET.ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.ID
     *
     * @param id the value for PUBLIC.TICKET.ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.IS_BOUGHT
     *
     * @return the value of PUBLIC.TICKET.IS_BOUGHT
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Boolean getIsBought() {
        return isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.IS_BOUGHT
     *
     * @param isBought the value for PUBLIC.TICKET.IS_BOUGHT
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setIsBought(Boolean isBought) {
        this.isBought = isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.PRICE
     *
     * @return the value of PUBLIC.TICKET.PRICE
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.PRICE
     *
     * @param price the value for PUBLIC.TICKET.PRICE
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.SEAT
     *
     * @return the value of PUBLIC.TICKET.SEAT
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.SEAT
     *
     * @param seat the value for PUBLIC.TICKET.SEAT
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setSeat(Integer seat) {
        this.seat = seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TICKET.TRIP_ID
     *
     * @return the value of PUBLIC.TICKET.TRIP_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getTripId() {
        return tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TICKET.TRIP_ID
     *
     * @param tripId the value for PUBLIC.TICKET.TRIP_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }
}