package task.lt.mybatis.model;

public class Trip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.ARRIVAL_TIME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private String arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.DEPARTURE_TIME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private String departureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.NAME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.BUS_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.DRIVER_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    private Integer driverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.ID
     *
     * @return the value of PUBLIC.TRIP.ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.ID
     *
     * @param id the value for PUBLIC.TRIP.ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.ARRIVAL_TIME
     *
     * @return the value of PUBLIC.TRIP.ARRIVAL_TIME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.ARRIVAL_TIME
     *
     * @param arrivalTime the value for PUBLIC.TRIP.ARRIVAL_TIME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.DEPARTURE_TIME
     *
     * @return the value of PUBLIC.TRIP.DEPARTURE_TIME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.DEPARTURE_TIME
     *
     * @param departureTime the value for PUBLIC.TRIP.DEPARTURE_TIME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.NAME
     *
     * @return the value of PUBLIC.TRIP.NAME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.NAME
     *
     * @param name the value for PUBLIC.TRIP.NAME
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.BUS_ID
     *
     * @return the value of PUBLIC.TRIP.BUS_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.BUS_ID
     *
     * @param busId the value for PUBLIC.TRIP.BUS_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.DRIVER_ID
     *
     * @return the value of PUBLIC.TRIP.DRIVER_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.DRIVER_ID
     *
     * @param driverId the value for PUBLIC.TRIP.DRIVER_ID
     *
     * @mbg.generated Mon Apr 25 12:52:10 EEST 2022
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }
}